biom convert -i /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.tsv -o /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.biom --to-hdf5 --table-type="OTU table"
qiime tools import --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.biom --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.qza --type FeatureTable[Frequency]
qiime sample-classifier classify-samples \
 --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.qza \
 --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/map.c0.tsv \
 --m-metadata-column Env \
 --p-cv 1 \
 --p-n-jobs 1 \
 --p-estimator RandomForestClassifier \
 --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/sample_estimator.qza \
 --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance.qza \
 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions.qza \
 --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/model_summary.qza \
 --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/accuracy_results.qzv \
 --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities.qza \
 --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.biom /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/tab.c0.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/sample_estimator.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/feature_importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/example/table_abund500/Snk-41A__Src-100B-692C/q2/RandomForestClassifier/c0/probabilities



