biom convert -i /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.tsv -o /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.biom --to-hdf5 --table-type="OTU table"
qiime tools import --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.biom --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --type FeatureTable[Frequency]
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r0/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r1/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r2/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r3/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r4/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r5/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r6/tab.pred.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/map.model.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/tab.model.qza
qiime sample-classifier classify-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/tab.model.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/map.model.tsv --m-metadata-column Env --p-cv 1 --p-n-jobs 1 --p-estimator RandomForestClassifier --o-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/sample_estimator.qza --o-feature-importance /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/feature_importance.qza --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions.qza --o-model-summary /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/model_summary.qzv --o-accuracy-results /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results.qzv --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities.qza --o-heatmap /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/heatmap.qzv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results.qzv --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results/predictions.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results_confusion.pdf
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results/roc_plot.pdf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results_roc.pdf
tail -n 3 /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results/predictive_accuracy.tsv > /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/feature_importance.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results.qzv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/accuracy_results
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/map.model.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/tab.model.qza
qiime feature-table filter-samples --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/tab.qza --m-metadata-file /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/map.pred.tsv --o-filtered-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/tab.pred.qza
qiime sample-classifier predict-classification --i-table /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/tab.pred.qza --i-sample-estimator /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/sample_estimator.qza --p-n-jobs 1 --o-predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions.qza --o-probabilities /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities.qza
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions.tsv
qiime tools export --input-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities.qza --output-path /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities
mv  /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities/* /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities.tsv
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/predictions /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities.qza /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/RandomForestClassifier/probabilities
rm -rf /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/map.pred.tsv /Users/flejzerowicz/programs/Xsourcetracking/Xsourcetracking/tests/nonstool745s/env_material-feces/q2/t0/r7/tab.pred.qza

